### PR TITLE
Add Typescript

### PR DESCRIPTION
**Pull request by mattwills8**
Hey! I'm using your package in our project, but I needed to convert it to typescript, so I thought I may as well go ahead and put in a PR to your repo with the changes I made.

The tests all pass, so this should be good to go. You'll need to run a build (I added an npm script) before publishing so npm has the required dist files :)

Very small unavoidable breaking change in the way we import, which has been documented in the readme. This only matters with `require` statements though, anyone doing `import Elo from 'elo-rank' should be fine.

Let me know if youre happy to merge this or if you need any changes made. Would be good to be able to switch over to it as a dependency in my project :D

### CODE REVIEW

**Comment by mattwills8** [comment]
It's failing for node v5 i think because yarn doesnt support it, maybe we could drop support for node v5? i think it's pretty ancient now

**Comment by dmamills** [comment]
Hey thanks for the PR!

I'm haven't used typescript much in my own work. But for your use case is it possible to just get a typescript definition file added to the repo? Would that allow for better integration without the need for rewriting the module in typescript?

**Comment by mattwills8** [comment]
@dmamills hey! Unfortunately it wouldnt really work like that, without having the actual module in ts it wouldnt properly integrate with full type coverage.  

Typescript is sort of a super set language that compiles to plain js, and checks for any possible type errors during that compilation process. You can choose what version of js to compile to, so I chose es2015, and if you check dist/index.js youll see the actual output is almost identical to your previous index.js file, just with the addition of that enum as an extra export.

It's a really really useful tool to have, and with a package this size it could be a perfect introduction to it for you, I'm still very new to it myself! :)

But obviously completely understand if it's not something you're interested in using... I suppose the alternative could be for me to set up a separate forked repo and npm package called 'elo-rank-typescript' or something, and maybe we could reference each other in our readmes?

**Comment by dmamills** [comment]
What I was suggesting was adding a `index.d.ts` file with something like:

```typescript
declare class EloRank {
	constructor(k: number);
	setKFactor(k: number);
	getKFactor() : number;
	getExpected(a: number, b: number) : number;
	updateRating(expected: number, actual: number, current: number) : number;
}
```

and adding `"types":"index.d.ts"` to the `package.json`. This should provide the typescript definitions for anyone using the package in a typescript environment. My understanding was this was the preferred method of adding type declarations to an existing javascript package. You can see the documentation about it [here.](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)

Alternatively you could publish the definitions as a package on it's own with the `@types` prefix. This is another popular method, more information is available [here.](https://definitelytyped.org/)

I'd mostly like to avoid add a transpiler to such a small package. I hope that helps provide some more context for you!

**Comment by mattwills8** [comment]
Yep, that's right, and if you run the build then those types will be automatically generated and the `index.d.ts` file will be created (almost exactly as you've written it above), along with the `index.js` file. I just didnt push the dist/ to the repo. Those type files are generated as a result of the compilation of the `index.ts` file, rather than being added manually. I think adding them manually would be a pain to maintain and very error prone.

I'd say it's the same issue with using DefinitelyTyped, if this package ever updates then the types will be out of sync. And the only way to make sure we regenerate the right types would be to again rewrite the package in ts and compile :/

**Comment by dmamills** [comment]
This repo was published about five years ago. In that time it has had one bug fix four years ago, and a small refactor to use the class keyword three years ago. Keeping updates in sync isn't really a big concern.

I'm appreciate your efforts on this PR, and have tried to accommodate your requests the best I can. But I'm not going to merge something that replaces the entire module with another subset of javascript that I don't even use.

**Comment by mattwills8** [comment]
No worries man, feel free to close, I'll set it up as a separate repo/pckg for people who want typescript :)

**Pull request closed without merging**
